name: icloud_storage
description: A flutter plugin for upload, download and manage files in the app's iCloud container.
version: 3.0.0
homepage: https://github.com/deansyd/icloud_storage

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: IcloudStoragePlugin
      macos:
        pluginClass: IcloudStoragePlugin
